### ISSUE TITLE
Can't attach debugger

### ISSUE THREAD

**Issue by andrei-sven** [facebook-atom/atom-ide-debugger-python#1]
Even though it's installed, when I try to attach the debugger, it sais that there are no debuggers installed.

And yet if I install a node debugger, I can see that one when I try to attach it.

**Atom**: 1.25.1
**OS**: Windows 10 Pro
**atom-ide-ui**: 0.11.0

**Comment by mostafaeweda** [comment]
This python debugger integration doesn’t yet support attach-ability (but can be easily modified to support it)

**Comment by Patlol** [comment]
Hello,
Atom 1.26.0
64 bits
linux mint 18.3

packages enable
atom-ide-ui 0.11.0
ide-python 0.9.2

I don't understand which python debugger to install with Atom  above packages.
I tried in particular
atom-ide-debugger-python 0.7.1
python-debugger 0.2.0
atom-python-debugger 0.3.4
but none is recognized

I have anyway the following message in attach debugger:
No debugger installed, look for available debugtger ...

The launch debugger window is filled as follows:
program: /home/patrick/Bureau/Pyprog/prog.py
python path: /usr/local/bin/python3.6
Cwd: /home/patrick/Bureau/Pyprog
Arg et Env : nothing

**Comment by mostafaeweda** [comment]
As I said, the current version doesn’t support attaching (only launching at this point) - but future versions may add it.

To launch python debugger using Atom IDE, you’d need the ‘atom-ide-debugger-python’

**Comment by mostafaeweda** [comment]
For documentation and list of supported debuggers, plz look at https://atom.io/packages/atom-ide-ui

**Comment by andrei-sven** [comment]
"As I said, the current version doesn’t support attaching (only launching at this point)"

Except when I try launching it, nothing happens. Or more accurately, it starts then immediately stops. I've got atom-ide-ui installed and atom-ide-debugger-python installed.

program: C:\Users\username\PycharmProjects\Tests\hydrogen_test.py
python path: C:\Users\username\AppData\Local\Programs\Python\Python36\python.exe
Cwd: C:\Users\username\PycharmProjects\Tests

**Comment by mostafaeweda** [comment]
This debugger engine is directly ported from VSCode's python debugger: https://github.com/DonJayamanne/pythonVSCode
Could you try and see if VSCode's debugger can debug this file / python version / environment?
