### ISSUE TITLE
debugger locks up at the end of execution

### ISSUE THREAD

**Issue by chrisrapson** [facebook-atom/atom-ide-debugger-python#5]
I am testing this debugger on a simple python file with a few print statements and incrementing an integer. It stops nicely at breakpoints, shows console output in a convenient sub-window and the watch expressions are nice. But when it gets to the end of the file, it seems to lock up. Hovering over the buttons for pause/step/stop comes up with a red circle. The hover text is unchanged for the step/stop buttons, but for pause it says "No running threads to pause!" I would expect it should change back to a play button in that case.

I haven't been able to find any way to reset the debugger and re-run it, besides restarting atom. I have tried

- clicking all the buttons, or their corresponding entries in the Debugger menu
- choosing "Restart the debugger" from the Debugger menu
- clearing the console
- closing and reopening the file

**Comment by mostafaeweda** [comment]
that doesn't look like a python-specific debugger issue - could you try nuclide - https://nuclide.io/ - and see if you got the same experience with all debuggers?

If so, please open an issue in https://github.com/facebook/nuclide
