### ISSUE TITLE
Can't attach debugger

### ISSUE THREAD

**Issue by kushwahashivam** [facebook-atom/atom-ide-debugger-python#6]
I have installed atom 1.28.1 on windows 10 Home x64

Then I installed atom-ide-ui
and then atom-ide-debugger-python

But I can't attach python debugger to my project.
It is showing-> No debugger installed.

Please solve this issue.

**Comment by mostafaeweda** [comment]
The current python debugger integration doesn't support attaching, see https://github.com/facebook-atom/atom-ide-debugger-python/issues/1
