### ISSUE TITLE
Input() Is not handled. 

### ISSUE THREAD

**Issue by marsfan** [facebook-atom/atom-ide-debugger-python#9]
Whenever my code has an `input()` function, the debugger gets to that line, and stops (likely waiting for user input), however, the prompt for user input never appears in the debugger console, and I cannot input data into the field.

I have both atom-ide-ui installed, as well as this addon. Python code runs fine, with the exception of the `input` function.

**Comment by ebluestein** [comment]
If you launch the script from the debugger dialog, it's running without a TTY present, so there is no STDIN hooked up to read from.  Any code that tries to read from STDIN will not work.

**Comment by Goom11** [comment]
@Marsfan, this has now been remedied. https://github.com/facebook/nuclide/commit/788a7604e73c250bdd9c7a522b912fb12d855342.

You will need to run your program using the Launch dialog and select the "integrated terminal" option for the console dialog field.

**Comment by marsfan** [comment]
@Goom11 Has this been brought over the atom-ide as well? I do not see it in my launch menu. 

![image](https://user-images.githubusercontent.com/9311953/47599565-d1d32480-d965-11e8-9d1b-1ef0c4558d83.png)

**Comment by Goom11** [comment]
I would think so. What version of atom-ide are you running?

**Comment by marsfan** [comment]
atom ide UI V 0.13.0. 
Atom-Debugger-Python version 0.7.3. 
No package updates listed. 

Windows 10, not sure if that helps.
